apiVersion: workloads.x-k8s.io/v1alpha1
kind: RoleBasedGroup
metadata:
  name: deepseek-rbg-deploy
  namespace: default
spec:
  roles:
    - name: prefill
      replicas: 1
      workload:
        apiVersion: leaderworkerset.x-k8s.io/v1
        kind: LeaderWorkerSet
      leaderWorkerSet:
        size: 2
        patchLeaderTemplate:
          metadata:
            labels:
              role: leader
              pd_role: prefill
          spec:
            containers:
              - command:
                  - >
                    python3 -m sglang.launch_server --model-path /work/models --trust-remote-code
                    --port 30000 --host 0.0.0.0
                    --dist-init-addr $(LWS_LEADER_ADDRESS):20102 
                    --nnodes $(LWS_GROUP_SIZE) 
                    --node-rank $(LWS_WORKER_INDEX) 
                    --context-length 32768 
                    --max-prefill-tokens 32768 
                    --max-running-requests 2048 
                    --chunked-prefill-size 393216 
                    --mem-fraction-static 0.76 
                    --disaggregation-mode prefill 
                    --disaggregation-ib-device mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7  
                    --disable-radix-cache
                    --page-size 64
                    --tp 16
                    --enable-dp-lm-head
                    --enable-dp-attention
                    --moe-dense-tp-size 1
                    --dp-size 16
                    --enable-deepep-moe
                    --deepep-mode normal
                    --ep-num-redundant-experts 32
                    --ep-dispatch-algorithm dynamic
                    --eplb-algorithm deepseek
                livenessProbe: &leaderLiveness
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: 30000
                  initialDelaySeconds: 300
                  periodSeconds: 60
                  successThreshold: 1
                  timeoutSeconds: 3
                readinessProbe: &leaderReadiness
                  failureThreshold: 20
                  httpGet:
                    path: /health
                    port: 30000
                  periodSeconds: 30
                  successThreshold: 1
                  timeoutSeconds: 3
                name: sglang
                ports:
                  - containerPort: 30000
                    name: sglang-http
                    protocol: TCP
        patchWorkerTemplate:
          spec:
            containers:
              - command:
                  - > 
                    python3 -m sglang.launch_server --model-path /work/models
                    --disable-radix-cache
                    --disaggregation-ib-device mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7
                    --chunked-prefill-size 393216
                    --page-size 64
                    --ep-dispatch-algorithm dynamic
                    --eplb-algorithm deepseek
                    --enable-dp-lm-head
                    --enable-dp-attention
                    --dp-size 16
                    --enable-deepep-moe
                    --deepep-mode normal
                    --disaggregation-mode prefill
                    --mem-fraction-static 0.76
                    --max-prefill-tokens 32768
                    --context-length 32768
                    --tp 16
                    --dist-init-addr $(LWS_LEADER_ADDRESS):20102
                    --nnodes $(LWS_GROUP_SIZE)
                    --node-rank $(LWS_WORKER_INDEX)
                    --trust-remote-code
                    --ep-num-redundant-experts 32
                    --moe-dense-tp-size 1
                    --max-running-requests 2048
                name: sglang
      template: &defaultPodTemplate
        metadata:
          labels:
            inference-framework: sglang
            inference-stack.io/monitoring: "enabled"
        spec:
          containers:
            - name: sglang
              image: sealos.hub:5000/sglang:v0.5.1.post1-cu126-fixip
              env:
                - name: CUDA_LAUNCH_BLOCKING
                  value: "0"
                - name:  SGLANG_DISAGGREGATION_BOOTSTRAP_TIMEOUT
                  value: "1000000000"
                - name: NVSHMEM_IB_TRAFFIC_CLASS
                  value: "16"
                - name: NVSHMEM_DISABLE_P2P
                  value: "0"
                - name: ENABLE_METRICS
                  value: "true"
                - name: NVSHMEM_IB_GID_INDEX
                  value: "3"
                - name: NVSHMEM_IB_SL
                  value: "5"
                - name: SGLANG_SET_CPU_AFFINITY
                  value: "true"
                - name: SGL_ENABLE_JIT_DEEPGEMM
                  value: "1"
                - name:  NCCL_IB_QPS_PER_CONNECTION
                  value: "8"
                - name: NCCL_IB_SPLIT_DATA_ON_QPS
                  value: "1"
                - name: NCCL_NET_PLUGIN
                  value: "none"
                - name: NCCL_IB_TC
                  value: "136"
                - name: NCCL_IB_SL
                  value: "5"
                - name: NCCL_IB_TIMEOUT
                  value: "22"
                - name: NCCL_IB_GID_INDEX
                  value: "3"
                - name: NCCL_MIN_NCHANNELS
                  value: "4"
                - name: NCCL_SOCKET_IFNAME
                  value: bond0
                - name: GLOO_SOCKET_IFNAME
                  value: bond0
                - name: NCCL_IB_HCA
                  value: ^=mlx5_0,mlx5_5,mlx5_6
                - name: NVSHMEM_BOOTSTRAP_UID_SOCK_IFNAME
                  value: "bond0"
                - name: MC_TE_METRIC
                  value: "false"
              resources:
                limits:
                  nvidia.com/gpu: "8"
              securityContext:
                capabilities:
                  add:
                    - IPC_LOCK
                privileged: true
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
          dnsPolicy: ClusterFirstWithHostNet
          volumes:
            - emptyDir:
                medium: Memory
              name: dshm

    - name: decode
      replicas: 1
      workload:
        apiVersion: leaderworkerset.x-k8s.io/v1
        kind: LeaderWorkerSet
      leaderWorkerSet:
        size: 4
        patchLeaderTemplate:
          metadata:
            labels:
              role: leader
              pd_role: decode
          spec:
            containers:
              - command:
                  - >
                    python3 -m sglang.launch_server --model-path /work/models
                    --port 30000 --host 0.0.0.0 
                    --disaggregation-ib-device mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7
                    --chunked-prefill-size 262144
                    --eplb-rebalance-layers-per-chunk 29
                    --page-size 64
                    --enable-dp-attention
                    --enable-dp-lm-head
                    --dp-size 32
                    --enable-deepep-moe
                    --deepep-mode low_latency
                    --disaggregation-mode decode
                    --mem-fraction-static 0.849
                    --context-length 32768
                    --cuda-graph-max-bs 64
                    --max-running-requests 4096
                    --tp-size 32
                    --dist-init-addr $(LWS_LEADER_ADDRESS):20102
                    --nnodes $(LWS_GROUP_SIZE)
                    --node-rank $(LWS_WORKER_INDEX)
                    --trust-remote-code
                    --ep-num-redundant-experts 32
                    --moe-dense-tp-size 1
                livenessProbe: *leaderLiveness
                name: sglang
                readinessProbe: *leaderReadiness
        patchWorkerTemplate:
          spec:
            containers:
              - command:
                  - >
                    python3 -m sglang.launch_server --model-path /work/models
                    --crash-dump-folder ./log
                    --chunked-prefill-size 262144
                    --eplb-rebalance-layers-per-chunk 29
                    --page-size 64
                    --enable-dp-attention
                    --enable-dp-lm-head
                    --dp-size 32
                    --enable-deepep-moe
                    --deepep-mode low_latency
                    --disaggregation-mode decode
                    --mem-fraction-static 0.849
                    --context-length 32768
                    --disaggregation-ib-device mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7
                    --cuda-graph-max-bs 64
                    --max-running-requests 4096
                    --tp-size 32  
                    --dist-init-addr $(LWS_LEADER_ADDRESS):20102
                    --nnodes $(LWS_GROUP_SIZE)
                    --node-rank $(LWS_WORKER_INDEX)
                    --trust-remote-code
                    --ep-num-redundant-experts 32
                    --moe-dense-tp-size 1
                name: sglang
      template: *defaultPodTemplate

    - name: router
      replicas: 1
      dependencies: [ "decode", "prefill" ]
      template:
        spec:
          containers:
            - name: scheduler
              image: sealos.hub:5000/sgl-router:dev
              command:
                - sh
                - -c
                - >
                  python3 -m sglang_router.launch_router
                  --host 0.0.0.0
                  --port 8080
                  --pd-disaggregation
                  --policy random
                  --service-discovery
                  --service-discovery-namespace ${NAMESPACE}
                  --service-discovery-port 30000
                  --prefill-selector pd_role=prefill
                  --decode-selector pd_role=decode
                  --max-payload-size 2147483648
                  --worker-startup-timeout-secs 1200
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deepseek-rbg-deploy
  name: deepseek-rbg-deploy
  namespace: default
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080
  selector:
    rolebasedgroup.workloads.x-k8s.io/name: deepseek-rbg-deploy
    rolebasedgroup.workloads.x-k8s.io/role: router
  type: NodePort